module.exports = [
  {
    format: '{{ticket}} {{crs}}',
    prompts: [
      {
        type: 'text',
        name: 'ticket',
        message: 'Enter ticket number',
        format: (ticketNumber) => (ticketNumber ? `#${ticketNumber}` : ''),
      },
      {
        type: 'multiselect',
        name: 'crs',
        message: 'Enter CRs (separated by ,)',
        format: (crs) => (crs ? `#cr@${crs}` : ''),
        choices: [
          ['Achia Rifman', 'achiar'],
          ['Alexander Gonchar', 'alexg'],
          ['Alex Kharkovskyi', 'aleksandrkh'],
          ['Alex Kononenko', 'alexko'],
          ['Amit Shalev', 'amitsh'],
          ['Amit Peer', 'amitp'],
          ['Anton Krapivner', 'antonkra'],
          ['Ariel Livshits', 'ariell'],
          ['Artem Petrov', 'artempe'],
          ['Assaf Barash', 'assafba'],
          ['Aviv Rosental', 'avivr'],
          ['Dor Duchovni', 'dord'],
          ['Dror Lapidot', 'drorl'],
          ['Elad Benitah', 'eladb'],
          ['Elad Weinson', 'eladu'],
          ['Elena Borisenko', 'elenabo'],
          ['Eran Shabi', 'erans'],
          ['Guy Segev', 'guyse'],
          ['Guy Warzager', 'varzager'],
          ['Hayden Marchant', 'haydenm'],
          ['Itay Avraham', 'itaya'],
          ['Itay Koren', 'itayk'],
          ['Julya Gofman', 'yolia'],
          ['Lior Ur', 'lioru'],
          ['Lior Waldman', 'liorwa'],
          ['Nachshon Schwartz', 'nachshons'],
          ['Naor Lipa', 'naorl'],
          ['Nitzan Sirota', 'nitzansi'],
          ['Nir Altmark', 'nira'],
          ['Oded Apel', 'odeda'],
          ['Ori Pinhas', 'oripi'],
          ['Ran Goldberg', 'rango'],
          ['Ronny Ringel', 'ronnyr'],
          ['Sagi Isha', 'sagii'],
          ['Sapir Hamtzani', 'sapirh'],
          ['Shahar Levi', 'shaharl'],
          ['Shai Drach', 'shaidr'],
          ['Shani Fedida', 'shanif'],
          ['Shilo Magen', 'shilomagen'],
          ['Tit Kovalenko', 'titk'],
          ['Tymofii Hrekov', 'tymofiih'],
          ['Zeev Glaizer', 'zeevg'],
        ].map(([title, value]) => ({ title, value })),
      },
    ],
  },
];
